# Generated by Django 5.0.4 on 2024-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining_items',
            field=models.IntegerField(default=0),
        ),
    ]
